// <auto-generated />
using System;
using Cassam.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cassam.Core.Persistence.Migrations
{
    [DbContext(typeof(CassamDbContext))]
    [Migration("20260624061202_DocumentoElectronicoEstadoCheck")]
    partial class DocumentoElectronicoEstadoCheck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cassam.Core.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("after_state");

                    b.Property<string>("BeforeState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("before_state");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_log_entity_type_entity_id");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_audit_log_tenant_id_id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_audit_log_tenant_id_occurred_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.CashSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<decimal?>("ClosingAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("closing_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("ExpectedAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("expected_amount");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by_user_id");

                    b.Property<decimal>("OpeningAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("opening_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("VarianceAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("variance_amount");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cash_sessions");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_cash_sessions_tenant_id_id");

                    b.HasIndex("TenantId", "OpenedByUserId")
                        .HasDatabaseName("ix_cash_sessions_tenant_id_opened_by_user_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_cash_sessions_tenant_id_status");

                    b.ToTable("cash_sessions", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CertStoreRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cert_store_ref");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("issuer");

                    b.Property<DateTime>("NotAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_after");

                    b.Property<DateTime>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PfxPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pfx_path");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_certificados");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_certificados_tenant_id_id");

                    b.HasIndex("TenantId", "Serial")
                        .IsUnique()
                        .HasDatabaseName("ix_certificados_tenant_id_serial");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_certificados_tenant_id_status");

                    b.ToTable("certificados", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.ContingencyQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DocumentoElectronicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_electronico_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_contingency_queue");

                    b.HasIndex("DocumentoElectronicoId")
                        .IsUnique()
                        .HasDatabaseName("ix_contingency_queue_documento_electronico_id");

                    b.HasIndex("TenantId", "QueuedAt")
                        .HasDatabaseName("ix_contingency_queue_tenant_id_queued_at");

                    b.ToTable("contingency_queue", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("document_type");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("person_type");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_customers_tenant_id_id");

                    b.HasIndex("TenantId", "DocumentType", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_tenant_id_document_type_document_number");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.DocumentoElectronico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CertificadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("certificado_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CufeOrCude")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cufe_or_cude");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("document_type");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pdf_path");

                    b.Property<Guid>("ResolucionId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolucion_id");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<string>("SignatureXml")
                        .HasColumnType("text")
                        .HasColumnName("signature_xml");

                    b.Property<Guid>("SoftwareTechnicalKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("software_technical_key_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("TransmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transmitted_at");

                    b.Property<string>("TransmittedResponseCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transmitted_response_code");

                    b.Property<string>("TransmittedResponseMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("transmitted_response_message");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid?>("VoidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("voided_by");

                    b.Property<string>("XmlPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("xml_payload");

                    b.HasKey("Id")
                        .HasName("pk_documentos_electronicos");

                    b.HasIndex("CertificadoId")
                        .HasDatabaseName("ix_documentos_electronicos_certificado_id");

                    b.HasIndex("ResolucionId")
                        .HasDatabaseName("ix_documentos_electronicos_resolucion_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_documentos_electronicos_sale_id");

                    b.HasIndex("SoftwareTechnicalKeyId")
                        .HasDatabaseName("ix_documentos_electronicos_software_technical_key_id");

                    b.HasIndex("VoidedBy")
                        .HasDatabaseName("ix_documentos_electronicos_voided_by");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_documentos_electronicos_tenant_id_id");

                    b.HasIndex("TenantId", "DocumentType", "CreatedAt")
                        .HasDatabaseName("ix_documentos_electronicos_tenant_id_document_type_created_at");

                    b.HasIndex("TenantId", "Estado", "CreatedAt")
                        .HasDatabaseName("ix_documentos_electronicos_tenant_id_estado_created_at");

                    b.ToTable("documentos_electronicos", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CashSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cash_session_id");

                    b.Property<decimal?>("ChangeAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("change_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<decimal?>("TenderedAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tendered_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("CashSessionId")
                        .HasDatabaseName("ix_payments_cash_session_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_payments_sale_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<decimal?>("StockQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("stock_quantity");

                    b.Property<string>("TaxCategory")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("tax_category");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("TenantId", "Barcode")
                        .HasDatabaseName("ix_products_tenant_id_barcode");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_products_tenant_id_id");

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_products_tenant_id_sku");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.Resolucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CurrentNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("current_number");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("document_type");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Prefix")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefix");

                    b.Property<long>("RangeEnd")
                        .HasColumnType("bigint")
                        .HasColumnName("range_end");

                    b.Property<long>("RangeStart")
                        .HasColumnType("bigint")
                        .HasColumnName("range_start");

                    b.Property<Guid>("SoftwareTechnicalKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("software_technical_key_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_resoluciones");

                    b.HasIndex("SoftwareTechnicalKeyId")
                        .HasDatabaseName("ix_resoluciones_software_technical_key_id");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_resoluciones_tenant_id_id");

                    b.HasIndex("TenantId", "DocumentType", "Prefix")
                        .IsUnique()
                        .HasDatabaseName("ix_resoluciones_tenant_id_document_type_prefix");

                    b.HasIndex("TenantId", "DocumentType", "Status")
                        .HasDatabaseName("ix_resoluciones_tenant_id_document_type_status");

                    b.ToTable("resoluciones", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CashSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cash_session_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("document_type");

                    b.Property<Guid?>("DocumentoElectronicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_electronico_id");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tax_total");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("CashSessionId")
                        .HasDatabaseName("ix_sales_cash_session_id");

                    b.HasIndex("TenantId", "CashSessionId")
                        .HasDatabaseName("ix_sales_tenant_id_cash_session_id");

                    b.HasIndex("TenantId", "DocumentType")
                        .HasDatabaseName("ix_sales_tenant_id_document_type");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_sales_tenant_id_id");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.SaleLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("LineTaxAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("line_tax_amount");

                    b.Property<string>("LineTaxCategory")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("line_tax_category");

                    b.Property<decimal>("LineTaxableAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("line_taxable_amount");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sale_line_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sale_line_items_product_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_line_items_sale_id");

                    b.ToTable("sale_line_items", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.SoftwareTechnicalKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<bool>("IssuedByDian")
                        .HasColumnType("boolean")
                        .HasColumnName("issued_by_dian");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_software_technical_keys");

                    b.HasIndex("TenantId", "Active")
                        .HasDatabaseName("ix_software_technical_keys_tenant_id_active");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_software_technical_keys_tenant_id_id");

                    b.ToTable("software_technical_keys", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CloudTransmissionEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("cloud_transmission_enabled");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubscriptionStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_started_at");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("subscription_tier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Nit")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_nit");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_email");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_users_tenant_id_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Cassam.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_tenants_tenant_id");
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.CashSession", b =>
                {
                    b.HasOne("Cassam.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cash_sessions_tenants_tenant_id");
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.Certificado", b =>
                {
                    b.HasOne("Cassam.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_certificados_tenants_tenant_id");
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.ContingencyQueue", b =>
                {
                    b.HasOne("Cassam.Core.Domain.Entities.DocumentoElectronico", null)
                        .WithMany()
                        .HasForeignKey("DocumentoElectronicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contingency_queue_documentos_electronicos_documento_electro");

                    b.HasOne("Cassam.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contingency_queue_tenants_tenant_id");
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Cassam.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customers_tenants_tenant_id");
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.DocumentoElectronico", b =>
                {
                    b.HasOne("Cassam.Core.Domain.Entities.Certificado", null)
                        .WithMany()
                        .HasForeignKey("CertificadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_electronicos_certificados_certificado_id");

                    b.HasOne("Cassam.Core.Domain.Entities.Resolucion", null)
                        .WithMany()
                        .HasForeignKey("ResolucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_electronicos_resoluciones_resolucion_id");

                    b.HasOne("Cassam.Core.Domain.Entities.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_documentos_electronicos_sales_sale_id");

                    b.HasOne("Cassam.Core.Domain.Entities.SoftwareTechnicalKey", null)
                        .WithMany()
                        .HasForeignKey("SoftwareTechnicalKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_electronicos_software_technical_keys_software_te");

                    b.HasOne("Cassam.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_electronicos_tenants_tenant_id");

                    b.HasOne("Cassam.Core.Domain.Entities.DocumentoElectronico", null)
                        .WithMany()
                        .HasForeignKey("VoidedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_documentos_electronicos_documentos_electronicos_voided_by");
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Cassam.Core.Domain.Entities.CashSession", null)
                        .WithMany()
                        .HasForeignKey("CashSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_cash_sessions_cash_session_id");

                    b.HasOne("Cassam.Core.Domain.Entities.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_sales_sale_id");
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.Product", b =>
                {
                    b.HasOne("Cassam.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_tenants_tenant_id");
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.Resolucion", b =>
                {
                    b.HasOne("Cassam.Core.Domain.Entities.SoftwareTechnicalKey", null)
                        .WithMany()
                        .HasForeignKey("SoftwareTechnicalKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resoluciones_software_technical_keys_software_technical_key");

                    b.HasOne("Cassam.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resoluciones_tenants_tenant_id");
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.Sale", b =>
                {
                    b.HasOne("Cassam.Core.Domain.Entities.CashSession", null)
                        .WithMany()
                        .HasForeignKey("CashSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_cash_sessions_cash_session_id");

                    b.HasOne("Cassam.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_tenants_tenant_id");
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.SaleLineItem", b =>
                {
                    b.HasOne("Cassam.Core.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sale_line_items_products_product_id");

                    b.HasOne("Cassam.Core.Domain.Entities.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sale_line_items_sales_sale_id");
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.SoftwareTechnicalKey", b =>
                {
                    b.HasOne("Cassam.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_software_technical_keys_tenants_tenant_id");
                });

            modelBuilder.Entity("Cassam.Core.Domain.Entities.User", b =>
                {
                    b.HasOne("Cassam.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
